"""Render content to images via the Octree LaTeX compile service."""

import logging
import os
import subprocess
import tempfile

import httpx

log = logging.getLogger(__name__)

COMPILE_URL = os.environ.get("COMPILE_URL", "https://compile.useoctree.com")
COMPILE_JWT = os.environ.get("COMPILE_JWT_TOKEN", "") or os.environ.get(
    "SUPABASE_SERVICE_ROLE_KEY", ""
)

POSTS_DIR = os.environ.get("POSTS_DIR", "/app/data/posts")


def _escape_latex(text: str) -> str:
    """Escape special LaTeX characters in plain text."""
    for ch in ("\\", "&", "%", "$", "#", "_", "{", "}"):
        text = text.replace(ch, f"\\{ch}")
    text = text.replace("~", r"\textasciitilde{}")
    text = text.replace("^", r"\textasciicircum{}")
    return text


def render_image(
    post_id: str,
    category: str,
    title: str,
    body: str,
    latex: str | None = None,
    code: str | None = None,
    code_language: str | None = None,
    hashtags: list[str] | None = None,
) -> str:
    """Render a LaTeX document to PNG via the Octree compile service."""
    os.makedirs(POSTS_DIR, exist_ok=True)
    out_path = os.path.join(POSTS_DIR, f"{post_id}.png")

    safe_title = _escape_latex(title)
    safe_body = _escape_latex(body)

    equation_block = ""
    if latex:
        equation_block = (
            "\\vspace{40pt}\n"
            "\\begin{center}\n"
            f"  $\\displaystyle {latex}$\n"
            "\\end{center}\n"
            "\\vspace{30pt}\n"
        )

    doc = (
        "\\documentclass[border=40pt]{standalone}\n"
        "\\usepackage{amsmath,amssymb,amsfonts}\n"
        "\\usepackage[dvipsnames]{xcolor}\n"
        "\\usepackage{graphicx}\n"
        "\\usepackage{varwidth}\n"
        "\n"
        "\\begin{document}\n"
        "\\begin{varwidth}{480pt}\n"
        "\\centering\n"
        "\\pagecolor[HTML]{1a1a2e}\n"
        "\\color{white}\n"
        "\n"
        "% Title\n"
        "{\\fontsize{28}{34}\\selectfont\\bfseries " + safe_title + "}\\par\n"
        "\n"
        "\\vspace{15pt}\n"
        "{\\color[HTML]{e94560}\\rule{80pt}{2pt}}\\par\n"
        "\n"
        "% Equation\n"
        "{\\fontsize{36}{44}\\selectfont\n"
        + equation_block +
        "}\\par\n"
        "\n"
        "% Description\n"
        "{\\fontsize{16}{22}\\selectfont\\color[HTML]{cccccc} " + safe_body + "}\\par\n"
        "\n"
        "\\vspace{40pt}\n"
        "% Branding\n"
        "{\\fontsize{20}{24}\\selectfont\\bfseries\\color[HTML]{e94560} Generated by useoctree.com}\\par\n"
        "\n"
        "\\end{varwidth}\n"
        "\\end{document}\n"
    )

    headers = {"Content-Type": "application/json"}
    if COMPILE_JWT:
        headers["Authorization"] = f"Bearer {COMPILE_JWT}"

    payload = {
        "files": [{"path": "main.tex", "content": doc}],
        "projectId": "scheduler-post",
    }

    try:
        resp = httpx.post(
            f"{COMPILE_URL}/compile",
            json=payload,
            headers=headers,
            timeout=30.0,
        )
        if resp.status_code != 200:
            raise RuntimeError(f"LaTeX compile failed ({resp.status_code}): {resp.text[:300]}")
    except httpx.HTTPError as e:
        raise RuntimeError(f"LaTeX compile request failed: {e}")

    # PDF -> PNG via pdftoppm
    with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as f:
        f.write(resp.content)
        pdf_path = f.name

    png_prefix = pdf_path.replace(".pdf", "")
    try:
        subprocess.run(
            ["pdftoppm", "-png", "-r", "300", "-singlefile", pdf_path, png_prefix],
            check=True,
            capture_output=True,
            timeout=15,
        )
        png_tmp = f"{png_prefix}.png"
        os.rename(png_tmp, out_path)
        log.info("Rendered image: %s", out_path)
        return out_path
    except (subprocess.CalledProcessError, FileNotFoundError) as e:
        raise RuntimeError(f"pdftoppm failed: {e}")
    finally:
        try:
            os.unlink(pdf_path)
        except OSError:
            pass
