"""Render content to images via the Octree LaTeX compile service.

Each content type gets a distinct LaTeX template. Colors rotate daily
from a pool of 12 palettes for maximum variety.
"""

import hashlib
import logging
import os
import shutil
import subprocess
import tempfile
from datetime import datetime, timezone

import httpx

log = logging.getLogger(__name__)

COMPILE_URL = os.environ.get("COMPILE_URL", "https://compile.useoctree.com")
COMPILE_JWT = os.environ.get("COMPILE_JWT_TOKEN", "") or os.environ.get(
    "SUPABASE_SERVICE_ROLE_KEY", ""
)

POSTS_DIR = os.environ.get("POSTS_DIR", "/app/data/posts")

# Fixed white-background palette: (bg, accent, muted_text)
COLOR_PALETTE = ("ffffff", "6A9FFF", "555555")


def _pick_palette(post_id: str) -> tuple[str, str, str]:
    """Return the fixed white-background palette."""
    return COLOR_PALETTE


def _escape_latex(text: str) -> str:
    """Escape special LaTeX characters in plain text."""
    for ch in ("\\", "&", "%", "$", "#", "_", "{", "}"):
        text = text.replace(ch, f"\\{ch}")
    text = text.replace("~", r"\textasciitilde{}")
    text = text.replace("^", r"\textasciicircum{}")
    return text


def _latex_preamble(bg_color: str) -> str:
    return (
        "\\documentclass[border=40pt]{standalone}\n"
        "\\usepackage{amsmath,amssymb,amsfonts}\n"
        "\\usepackage[dvipsnames]{xcolor}\n"
        "\\usepackage{graphicx}\n"
        "\\usepackage{varwidth}\n"
        "\\usepackage{listings}\n"
        "\n"
        "\\begin{document}\n"
        "\\begin{varwidth}{480pt}\n"
        "\\centering\n"
        f"\\pagecolor[HTML]{{{bg_color}}}\n"
        "\\color{black}\n\n"
    )


def _latex_footer() -> str:
    return "\\end{varwidth}\n\\end{document}\n"


def _branding(accent: str) -> str:
    return (
        "\\vspace{40pt}\n"
        f"{{\\fontsize{{20}}{{24}}\\selectfont\\bfseries\\color[HTML]{{{accent}}} "
        "Generated by useoctree.com}\\par\n"
    )


# ── Templates ────────────────────────────────────────────────────

def _template_equation(content: dict, bg: str, accent: str, muted: str) -> str:
    title = _escape_latex(content["title"])
    body = _escape_latex(content["body"])
    latex = content.get("latex", "")

    eq_block = ""
    if latex:
        eq_block = (
            "\\vspace{40pt}\n"
            "\\begin{center}\n"
            f"  $\\displaystyle {latex}$\n"
            "\\end{center}\n"
            "\\vspace{30pt}\n"
        )

    return (
        _latex_preamble(bg)
        + f"{{\\fontsize{{28}}{{34}}\\selectfont\\bfseries {title}}}\\par\n"
        "\\vspace{15pt}\n"
        f"{{\\color[HTML]{{{accent}}}\\rule{{80pt}}{{2pt}}}}\\par\n"
        f"{{\\fontsize{{36}}{{44}}\\selectfont\n{eq_block}}}\\par\n"
        f"{{\\fontsize{{16}}{{22}}\\selectfont\\color[HTML]{{{muted}}} {body}}}\\par\n"
        + _branding(accent)
        + _latex_footer()
    )


def _template_code_snippet(content: dict, bg: str, accent: str, muted: str) -> str:
    title = _escape_latex(content["title"])
    body = _escape_latex(content["body"])
    code = content.get("code", "# no code")
    lang = content.get("code_language", "Python")

    return (
        _latex_preamble(bg)
        + f"{{\\fontsize{{26}}{{32}}\\selectfont\\bfseries {title}}}\\par\n"
        "\\vspace{10pt}\n"
        f"{{\\color[HTML]{{{accent}}}\\rule{{80pt}}{{2pt}}}}\\par\n"
        "\\vspace{5pt}\n"
        f"{{\\fontsize{{14}}{{18}}\\selectfont\\bfseries\\color[HTML]{{{accent}}} {_escape_latex(lang)}}}\\par\n"
        "\\vspace{10pt}\n"
        "{\\ttfamily\\fontsize{13}{17}\\selectfont\\color[HTML]{222222}\n"
        f"\\begin{{verbatim}}\n{code}\n\\end{{verbatim}}\n"
        "}\\par\n"
        "\\vspace{10pt}\n"
        f"{{\\fontsize{{16}}{{22}}\\selectfont\\color[HTML]{{{muted}}} {body}}}\\par\n"
        + _branding(accent)
        + _latex_footer()
    )


def _template_definition(content: dict, bg: str, accent: str, muted: str) -> str:
    title = _escape_latex(content["title"])
    body = _escape_latex(content["body"])
    key_term = _escape_latex(content.get("key_term", title))

    return (
        _latex_preamble(bg)
        + f"{{\\fontsize{{18}}{{22}}\\selectfont\\color[HTML]{{{accent}}} DEFINITION}}\\par\n"
        "\\vspace{10pt}\n"
        f"{{\\color[HTML]{{{accent}}}\\rule{{80pt}}{{2pt}}}}\\par\n"
        "\\vspace{20pt}\n"
        f"{{\\fontsize{{34}}{{42}}\\selectfont\\bfseries {key_term}}}\\par\n"
        "\\vspace{30pt}\n"
        f"{{\\fontsize{{18}}{{26}}\\selectfont\\color[HTML]{{{muted}}} {body}}}\\par\n"
        + _branding(accent)
        + _latex_footer()
    )


def _template_fact(content: dict, bg: str, accent: str, muted: str) -> str:
    title = _escape_latex(content["title"])
    body = _escape_latex(content["body"])
    big_number = _escape_latex(content.get("big_number", "?"))

    return (
        _latex_preamble(bg)
        + f"{{\\fontsize{{18}}{{22}}\\selectfont\\color[HTML]{{{accent}}} DID YOU KNOW?}}\\par\n"
        "\\vspace{10pt}\n"
        f"{{\\color[HTML]{{{accent}}}\\rule{{80pt}}{{2pt}}}}\\par\n"
        "\\vspace{30pt}\n"
        f"{{\\fontsize{{52}}{{60}}\\selectfont\\bfseries\\color[HTML]{{{accent}}} {big_number}}}\\par\n"
        "\\vspace{25pt}\n"
        f"{{\\fontsize{{24}}{{30}}\\selectfont\\bfseries {title}}}\\par\n"
        "\\vspace{20pt}\n"
        f"{{\\fontsize{{16}}{{22}}\\selectfont\\color[HTML]{{{muted}}} {body}}}\\par\n"
        + _branding(accent)
        + _latex_footer()
    )


def _template_quote(content: dict, bg: str, accent: str, muted: str) -> str:
    body = _escape_latex(content["body"])
    attribution = _escape_latex(content.get("attribution", "Unknown"))

    return (
        _latex_preamble(bg)
        + f"{{\\fontsize{{48}}{{48}}\\selectfont\\color[HTML]{{{accent}}} ``}}\\par\n"
        "\\vspace{10pt}\n"
        f"{{\\fontsize{{24}}{{34}}\\selectfont\\itshape {body}}}\\par\n"
        "\\vspace{25pt}\n"
        f"{{\\color[HTML]{{{accent}}}\\rule{{60pt}}{{2pt}}}}\\par\n"
        "\\vspace{15pt}\n"
        f"{{\\fontsize{{18}}{{22}}\\selectfont\\color[HTML]{{{muted}}} --- {attribution}}}\\par\n"
        + _branding(accent)
        + _latex_footer()
    )


def _template_resume(content: dict, bg: str, accent: str, muted: str) -> str:
    name = _escape_latex(content.get("name", "Jane Doe"))
    job_title = _escape_latex(content.get("job_title", "Software Engineer"))
    achievements = content.get("achievements", [])
    skills = content.get("skills", [])

    ach_items = "\n".join(
        f"  \\item {{\\color{{black}} {_escape_latex(a)}}}" for a in achievements[:4]
    )
    skills_str = _escape_latex(" | ".join(skills[:8]))

    return (
        _latex_preamble(bg)
        + f"{{\\fontsize{{14}}{{18}}\\selectfont\\color[HTML]{{{accent}}} RESUME — BUILT WITH \\LaTeX}}\\par\n"
        "\\vspace{15pt}\n"
        f"{{\\color[HTML]{{{accent}}}\\rule{{320pt}}{{1.5pt}}}}\\par\n"
        "\\vspace{15pt}\n"
        f"{{\\fontsize{{32}}{{38}}\\selectfont\\bfseries {name}}}\\par\n"
        "\\vspace{5pt}\n"
        f"{{\\fontsize{{18}}{{22}}\\selectfont\\color[HTML]{{{muted}}} {job_title}}}\\par\n"
        "\\vspace{20pt}\n"
        f"{{\\fontsize{{16}}{{20}}\\selectfont\\bfseries\\color[HTML]{{{accent}}} EXPERIENCE}}\\par\n"
        "\\vspace{8pt}\n"
        "\\begin{itemize}\n"
        "\\setlength{\\itemsep}{6pt}\n"
        f"{{\\fontsize{{14}}{{19}}\\selectfont\n{ach_items}\n}}\n"
        "\\end{itemize}\n"
        "\\vspace{15pt}\n"
        f"{{\\fontsize{{16}}{{20}}\\selectfont\\bfseries\\color[HTML]{{{accent}}} SKILLS}}\\par\n"
        "\\vspace{8pt}\n"
        f"{{\\fontsize{{13}}{{18}}\\selectfont\\color[HTML]{{{muted}}} {skills_str}}}\\par\n"
        + _branding(accent)
        + _latex_footer()
    )


def _template_presentation(content: dict, bg: str, accent: str, muted: str) -> str:
    slide_title = _escape_latex(content.get("slide_title", content["title"]))
    bullets = content.get("bullets", [])
    slide_eq = content.get("slide_equation", "")

    bullet_items = "\n".join(
        f"  \\item {{\\color{{black}} {_escape_latex(b)}}}" for b in bullets[:5]
    )

    eq_block = ""
    if slide_eq:
        eq_block = (
            "\\vspace{15pt}\n"
            "\\begin{center}\n"
            f"  $\\displaystyle {slide_eq}$\n"
            "\\end{center}\n"
        )

    return (
        _latex_preamble(bg)
        + f"{{\\fontsize{{14}}{{18}}\\selectfont\\color[HTML]{{{accent}}} PRESENTATION SLIDE}}\\par\n"
        "\\vspace{10pt}\n"
        f"{{\\color[HTML]{{{accent}}}\\rule{{360pt}}{{2pt}}}}\\par\n"
        "\\vspace{20pt}\n"
        f"{{\\fontsize{{30}}{{36}}\\selectfont\\bfseries {slide_title}}}\\par\n"
        "\\vspace{20pt}\n"
        "\\begin{itemize}\n"
        "\\setlength{\\itemsep}{8pt}\n"
        f"{{\\fontsize{{16}}{{22}}\\selectfont\n{bullet_items}\n}}\n"
        "\\end{itemize}\n"
        f"{eq_block}"
        + _branding(accent)
        + _latex_footer()
    )


def _template_research(content: dict, bg: str, accent: str, muted: str) -> str:
    title = _escape_latex(content["title"])
    authors = content.get("authors", ["Unknown"])
    institution = _escape_latex(content.get("institution", ""))
    body = _escape_latex(content["body"])
    key_eq = content.get("key_equation", "")

    authors_str = _escape_latex(", ".join(authors))

    eq_block = ""
    if key_eq:
        eq_block = (
            "\\vspace{15pt}\n"
            "\\begin{center}\n"
            f"  $\\displaystyle {key_eq}$\n"
            "\\end{center}\n"
            "\\vspace{10pt}\n"
        )

    return (
        _latex_preamble(bg)
        + f"{{\\fontsize{{14}}{{18}}\\selectfont\\color[HTML]{{{accent}}} RESEARCH PAPER}}\\par\n"
        "\\vspace{10pt}\n"
        f"{{\\color[HTML]{{{accent}}}\\rule{{320pt}}{{1.5pt}}}}\\par\n"
        "\\vspace{20pt}\n"
        f"{{\\fontsize{{26}}{{32}}\\selectfont\\bfseries {title}}}\\par\n"
        "\\vspace{10pt}\n"
        f"{{\\fontsize{{14}}{{18}}\\selectfont\\color[HTML]{{{muted}}} {authors_str}}}\\par\n"
        "\\vspace{3pt}\n"
        f"{{\\fontsize{{12}}{{16}}\\selectfont\\itshape\\color[HTML]{{{muted}}} {institution}}}\\par\n"
        "\\vspace{20pt}\n"
        f"{{\\fontsize{{16}}{{20}}\\selectfont\\bfseries\\color[HTML]{{{accent}}} Abstract}}\\par\n"
        "\\vspace{8pt}\n"
        f"{{\\fontsize{{14}}{{20}}\\selectfont\\color[HTML]{{{muted}}} {body}}}\\par\n"
        f"{eq_block}"
        + _branding(accent)
        + _latex_footer()
    )


TEMPLATES = {
    "equation": _template_equation,
    "code_snippet": _template_code_snippet,
    "definition": _template_definition,
    "fact": _template_fact,
    "quote": _template_quote,
    "resume": _template_resume,
    "presentation": _template_presentation,
    "research": _template_research,
}


# ── Public API ───────────────────────────────────────────────────

def render_image(
    post_id: str,
    category: str,
    title: str,
    body: str,
    latex: str | None = None,
    code: str | None = None,
    code_language: str | None = None,
    hashtags: list[str] | None = None,
    content: dict | None = None,
) -> str:
    """Render a LaTeX document to PNG via the Octree compile service."""
    os.makedirs(POSTS_DIR, exist_ok=True)
    out_path = os.path.join(POSTS_DIR, f"{post_id}.png")

    if content is None:
        content = {
            "content_type": "equation",
            "title": title,
            "body": body,
            "latex": latex,
            "code": code,
            "code_language": code_language,
        }

    content_type = content.get("content_type", "equation")
    template_fn = TEMPLATES.get(content_type, _template_equation)

    # Pick colors based on post_id for daily variety
    bg, accent, muted = _pick_palette(post_id)
    doc = template_fn(content, bg, accent, muted)

    headers = {"Content-Type": "application/json"}
    if COMPILE_JWT:
        headers["Authorization"] = f"Bearer {COMPILE_JWT}"

    payload = {
        "files": [{"path": "main.tex", "content": doc}],
        "projectId": "scheduler-post",
    }

    try:
        resp = httpx.post(
            f"{COMPILE_URL}/compile",
            json=payload,
            headers=headers,
            timeout=30.0,
        )
        # Even on non-200, the PDF may still be in the response body
        has_pdf = resp.content[:5] == b"%PDF-"
        if resp.status_code != 200 and not has_pdf:
            raise RuntimeError(f"LaTeX compile failed ({resp.status_code}): {resp.text[:300]}")
        if resp.status_code != 200 and has_pdf:
            log.warning("LaTeX compile returned %d but PDF was generated, proceeding", resp.status_code)
    except httpx.HTTPError as e:
        raise RuntimeError(f"LaTeX compile request failed: {e}")

    # PDF -> PNG via pdftoppm
    with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as f:
        f.write(resp.content)
        pdf_path = f.name

    png_prefix = pdf_path.replace(".pdf", "")
    try:
        subprocess.run(
            ["pdftoppm", "-png", "-r", "300", "-singlefile", pdf_path, png_prefix],
            check=True,
            capture_output=True,
            timeout=15,
        )
        png_tmp = f"{png_prefix}.png"
        shutil.move(png_tmp, out_path)
        log.info("Rendered image: %s", out_path)
        return out_path
    except (subprocess.CalledProcessError, FileNotFoundError) as e:
        raise RuntimeError(f"pdftoppm failed: {e}")
    finally:
        try:
            os.unlink(pdf_path)
        except OSError:
            pass
