"""Render content to images via the Octree LaTeX compile service.

Each content type gets a distinct LaTeX template. Colors rotate daily
from a pool of 12 palettes for maximum variety.
"""

import hashlib
import logging
import os
import shutil
import subprocess
import tempfile
from datetime import datetime, timezone

import httpx

log = logging.getLogger(__name__)

COMPILE_URL = os.environ.get("COMPILE_URL", "https://compile.useoctree.com")
COMPILE_JWT = os.environ.get("COMPILE_JWT_TOKEN", "") or os.environ.get(
    "SUPABASE_SERVICE_ROLE_KEY", ""
)

POSTS_DIR = os.environ.get("POSTS_DIR", "/app/data/posts")

# 12 color palettes: (bg, accent, muted_text)
# Rotated based on post_id hash so every post looks different
COLOR_PALETTES = [
    ("1a1a2e", "e94560", "cccccc"),   # navy + crimson
    ("0d1117", "58a6ff", "8b949e"),   # github dark + blue
    ("0f0c29", "24fe41", "b0b0b0"),   # deep indigo + neon green
    ("2d1b69", "f8e71c", "d0c4f7"),   # purple + gold
    ("1b1b2f", "e43f5a", "9e9eb8"),   # dark blue + coral
    ("0a0a23", "f5a623", "a0a0c0"),   # midnight + orange
    ("0c0032", "7b2ff7", "c0b0e0"),   # dark violet + purple
    ("1a1a1a", "ff6b35", "bbbbbb"),   # charcoal + burnt orange
    ("0b132b", "3a86ff", "a0b4d0"),   # navy + bright blue
    ("1c1c3c", "ff006e", "c0b0c8"),   # dark + hot pink
    ("0d1b2a", "00f5d4", "90c0b0"),   # dark teal + cyan
    ("191919", "ffd166", "b8b8b8"),   # black + warm yellow
]


def _pick_palette(post_id: str) -> tuple[str, str, str]:
    """Pick a color palette based on post_id hash for variety."""
    h = int(hashlib.md5(post_id.encode()).hexdigest(), 16)
    return COLOR_PALETTES[h % len(COLOR_PALETTES)]


def _escape_latex(text: str) -> str:
    """Escape special LaTeX characters in plain text."""
    for ch in ("\\", "&", "%", "$", "#", "_", "{", "}"):
        text = text.replace(ch, f"\\{ch}")
    text = text.replace("~", r"\textasciitilde{}")
    text = text.replace("^", r"\textasciicircum{}")
    return text


def _latex_preamble(bg_color: str) -> str:
    return (
        "\\documentclass[border=40pt]{standalone}\n"
        "\\usepackage{amsmath,amssymb,amsfonts}\n"
        "\\usepackage[dvipsnames]{xcolor}\n"
        "\\usepackage{graphicx}\n"
        "\\usepackage{varwidth}\n"
        "\\usepackage{listings}\n"
        "\n"
        "\\begin{document}\n"
        "\\begin{varwidth}{480pt}\n"
        "\\centering\n"
        f"\\pagecolor[HTML]{{{bg_color}}}\n"
        "\\color{white}\n\n"
    )


def _latex_footer() -> str:
    return "\\end{varwidth}\n\\end{document}\n"


def _branding(accent: str) -> str:
    return (
        "\\vspace{40pt}\n"
        f"{{\\fontsize{{20}}{{24}}\\selectfont\\bfseries\\color[HTML]{{{accent}}} "
        "Generated by useoctree.com}\\par\n"
    )


# ── Templates ────────────────────────────────────────────────────

def _template_equation(content: dict, bg: str, accent: str, muted: str) -> str:
    title = _escape_latex(content["title"])
    body = _escape_latex(content["body"])
    latex = content.get("latex", "")

    eq_block = ""
    if latex:
        eq_block = (
            "\\vspace{40pt}\n"
            "\\begin{center}\n"
            f"  $\\displaystyle {latex}$\n"
            "\\end{center}\n"
            "\\vspace{30pt}\n"
        )

    return (
        _latex_preamble(bg)
        + f"{{\\fontsize{{28}}{{34}}\\selectfont\\bfseries {title}}}\\par\n"
        "\\vspace{15pt}\n"
        f"{{\\color[HTML]{{{accent}}}\\rule{{80pt}}{{2pt}}}}\\par\n"
        f"{{\\fontsize{{36}}{{44}}\\selectfont\n{eq_block}}}\\par\n"
        f"{{\\fontsize{{16}}{{22}}\\selectfont\\color[HTML]{{{muted}}} {body}}}\\par\n"
        + _branding(accent)
        + _latex_footer()
    )


def _template_code_snippet(content: dict, bg: str, accent: str, muted: str) -> str:
    title = _escape_latex(content["title"])
    body = _escape_latex(content["body"])
    code = content.get("code", "# no code")
    lang = content.get("code_language", "Python")

    return (
        _latex_preamble(bg)
        + "\\lstset{\n"
        "  basicstyle=\\ttfamily\\fontsize{14}{18}\\selectfont\\color[HTML]{e6edf3},\n"
        f"  backgroundcolor=\\color[HTML]{{{bg}}},\n"
        "  frame=single,\n"
        f"  rulecolor=\\color[HTML]{{{accent}}},\n"
        f"  keywordstyle=\\color[HTML]{{{accent}}},\n"
        "  stringstyle=\\color[HTML]{a5d6ff},\n"
        f"  commentstyle=\\color[HTML]{{{muted}}},\n"
        "  breaklines=true,\n"
        "  showstringspaces=false,\n"
        "  xleftmargin=10pt,\n"
        "  xrightmargin=10pt,\n"
        "  aboveskip=15pt,\n"
        "  belowskip=15pt,\n"
        "  extendedchars=true,\n"
        "  columns=fullflexible,\n"
        "  keepspaces=true,\n"
        "  literate={<}{\\textless}1 {>}{\\textgreater}1 {|}{\\textbar}1 {~}{\\textasciitilde}1,\n"
        "}\n\n"
        f"{{\\fontsize{{26}}{{32}}\\selectfont\\bfseries {title}}}\\par\n"
        "\\vspace{10pt}\n"
        f"{{\\color[HTML]{{{accent}}}\\rule{{80pt}}{{2pt}}}}\\par\n"
        "\\vspace{5pt}\n"
        f"{{\\fontsize{{14}}{{18}}\\selectfont\\bfseries\\color[HTML]{{{accent}}} {_escape_latex(lang)}}}\\par\n"
        "\\vspace{10pt}\n"
        f"\\begin{{lstlisting}}\n{code}\n\\end{{lstlisting}}\n"
        "\\vspace{10pt}\n"
        f"{{\\fontsize{{16}}{{22}}\\selectfont\\color[HTML]{{{muted}}} {body}}}\\par\n"
        + _branding(accent)
        + _latex_footer()
    )


def _template_definition(content: dict, bg: str, accent: str, muted: str) -> str:
    title = _escape_latex(content["title"])
    body = _escape_latex(content["body"])
    key_term = _escape_latex(content.get("key_term", title))

    return (
        _latex_preamble(bg)
        + f"{{\\fontsize{{18}}{{22}}\\selectfont\\color[HTML]{{{accent}}} DEFINITION}}\\par\n"
        "\\vspace{10pt}\n"
        f"{{\\color[HTML]{{{accent}}}\\rule{{80pt}}{{2pt}}}}\\par\n"
        "\\vspace{20pt}\n"
        f"{{\\fontsize{{34}}{{42}}\\selectfont\\bfseries {key_term}}}\\par\n"
        "\\vspace{30pt}\n"
        f"{{\\fontsize{{18}}{{26}}\\selectfont\\color[HTML]{{{muted}}} {body}}}\\par\n"
        + _branding(accent)
        + _latex_footer()
    )


def _template_fact(content: dict, bg: str, accent: str, muted: str) -> str:
    title = _escape_latex(content["title"])
    body = _escape_latex(content["body"])
    big_number = _escape_latex(content.get("big_number", "?"))

    return (
        _latex_preamble(bg)
        + f"{{\\fontsize{{18}}{{22}}\\selectfont\\color[HTML]{{{accent}}} DID YOU KNOW?}}\\par\n"
        "\\vspace{10pt}\n"
        f"{{\\color[HTML]{{{accent}}}\\rule{{80pt}}{{2pt}}}}\\par\n"
        "\\vspace{30pt}\n"
        f"{{\\fontsize{{52}}{{60}}\\selectfont\\bfseries\\color[HTML]{{{accent}}} {big_number}}}\\par\n"
        "\\vspace{25pt}\n"
        f"{{\\fontsize{{24}}{{30}}\\selectfont\\bfseries {title}}}\\par\n"
        "\\vspace{20pt}\n"
        f"{{\\fontsize{{16}}{{22}}\\selectfont\\color[HTML]{{{muted}}} {body}}}\\par\n"
        + _branding(accent)
        + _latex_footer()
    )


def _template_quote(content: dict, bg: str, accent: str, muted: str) -> str:
    body = _escape_latex(content["body"])
    attribution = _escape_latex(content.get("attribution", "Unknown"))

    return (
        _latex_preamble(bg)
        + f"{{\\fontsize{{48}}{{48}}\\selectfont\\color[HTML]{{{accent}}} ``}}\\par\n"
        "\\vspace{10pt}\n"
        f"{{\\fontsize{{24}}{{34}}\\selectfont\\itshape {body}}}\\par\n"
        "\\vspace{25pt}\n"
        f"{{\\color[HTML]{{{accent}}}\\rule{{60pt}}{{2pt}}}}\\par\n"
        "\\vspace{15pt}\n"
        f"{{\\fontsize{{18}}{{22}}\\selectfont\\color[HTML]{{{muted}}} --- {attribution}}}\\par\n"
        + _branding(accent)
        + _latex_footer()
    )


TEMPLATES = {
    "equation": _template_equation,
    "code_snippet": _template_code_snippet,
    "definition": _template_definition,
    "fact": _template_fact,
    "quote": _template_quote,
}


# ── Public API ───────────────────────────────────────────────────

def render_image(
    post_id: str,
    category: str,
    title: str,
    body: str,
    latex: str | None = None,
    code: str | None = None,
    code_language: str | None = None,
    hashtags: list[str] | None = None,
    content: dict | None = None,
) -> str:
    """Render a LaTeX document to PNG via the Octree compile service."""
    os.makedirs(POSTS_DIR, exist_ok=True)
    out_path = os.path.join(POSTS_DIR, f"{post_id}.png")

    if content is None:
        content = {
            "content_type": "equation",
            "title": title,
            "body": body,
            "latex": latex,
            "code": code,
            "code_language": code_language,
        }

    content_type = content.get("content_type", "equation")
    template_fn = TEMPLATES.get(content_type, _template_equation)

    # Pick colors based on post_id for daily variety
    bg, accent, muted = _pick_palette(post_id)
    doc = template_fn(content, bg, accent, muted)

    headers = {"Content-Type": "application/json"}
    if COMPILE_JWT:
        headers["Authorization"] = f"Bearer {COMPILE_JWT}"

    payload = {
        "files": [{"path": "main.tex", "content": doc}],
        "projectId": "scheduler-post",
    }

    try:
        resp = httpx.post(
            f"{COMPILE_URL}/compile",
            json=payload,
            headers=headers,
            timeout=30.0,
        )
        if resp.status_code != 200:
            raise RuntimeError(f"LaTeX compile failed ({resp.status_code}): {resp.text[:300]}")
    except httpx.HTTPError as e:
        raise RuntimeError(f"LaTeX compile request failed: {e}")

    # PDF -> PNG via pdftoppm
    with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as f:
        f.write(resp.content)
        pdf_path = f.name

    png_prefix = pdf_path.replace(".pdf", "")
    try:
        subprocess.run(
            ["pdftoppm", "-png", "-r", "300", "-singlefile", pdf_path, png_prefix],
            check=True,
            capture_output=True,
            timeout=15,
        )
        png_tmp = f"{png_prefix}.png"
        shutil.move(png_tmp, out_path)
        log.info("Rendered image: %s", out_path)
        return out_path
    except (subprocess.CalledProcessError, FileNotFoundError) as e:
        raise RuntimeError(f"pdftoppm failed: {e}")
    finally:
        try:
            os.unlink(pdf_path)
        except OSError:
            pass
